// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PesquisaEleitoral.Data;

#nullable disable

namespace PesquisaEleitoral.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410143231_AlteracaoDoEleitor")]
    partial class AlteracaoDoEleitor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PesquisaEleitoral.Models.Candidato", b =>
                {
                    b.Property<int>("CandidatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CandidatoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Partido")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.HasKey("CandidatoId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("PesquisaEleitoral.Models.Eleitor", b =>
                {
                    b.Property<int>("EleitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EleitorId"));

                    b.Property<int>("Escolaridade")
                        .HasColumnType("int");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Regiao")
                        .HasColumnType("int");

                    b.Property<decimal>("Renda")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.HasKey("EleitorId");

                    b.ToTable("Eleitores");
                });

            modelBuilder.Entity("PesquisaEleitoral.Models.IntencaoDeVoto", b =>
                {
                    b.Property<int>("IntencaoDeVotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IntencaoDeVotoId"));

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EleitorId")
                        .HasColumnType("int");

                    b.HasKey("IntencaoDeVotoId");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EleitorId")
                        .IsUnique();

                    b.ToTable("IntencoesDeVoto");
                });

            modelBuilder.Entity("PesquisaEleitoral.Models.IntencaoDeVoto", b =>
                {
                    b.HasOne("PesquisaEleitoral.Models.Candidato", "Candidato")
                        .WithMany("IntencaoDeVoto")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PesquisaEleitoral.Models.Eleitor", "Eleitor")
                        .WithOne("IntencaoDeVoto")
                        .HasForeignKey("PesquisaEleitoral.Models.IntencaoDeVoto", "EleitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Eleitor");
                });

            modelBuilder.Entity("PesquisaEleitoral.Models.Candidato", b =>
                {
                    b.Navigation("IntencaoDeVoto");
                });

            modelBuilder.Entity("PesquisaEleitoral.Models.Eleitor", b =>
                {
                    b.Navigation("IntencaoDeVoto");
                });
#pragma warning restore 612, 618
        }
    }
}
